[package]
name = "hyperonc"
version = "0.1.6"
authors = ["Vitaly Bogdanov <vsbogd@gmail.com>"]
edition = "2018"

[dependencies]
hyperon = { path = "../lib/" }
regex = "1.5.4"
log = "0.4.0"
env_logger = "0.8.4"

[lib]
name = "hyperonc"
path = "src/lib.rs"
crate-type = ["cdylib", "staticlib"]
