[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "hyperon"
version = "0.1.2"
description = "Hyperon API in Python"
requires-python = ">=3.7"
keywords = ["metta", "hyperon", "opencog"]
license = {text = "MIT License"}
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Development Status :: 2 - Pre-Alpha",
    "Operating System :: POSIX :: Linux",
    "Operating System :: MacOS :: MacOS X",
]
dependencies = [
    'importlib-metadata; python_version<"3.8"',
]

[project.scripts]
metta = "hyperon:main"

[project.optional-dependencies]
dev = [
    "coverage",
]

[tool.setuptools]
packages = [ "hyperon" ]
package-dir = { "hyperon" = "hyperon" }

[tool.setuptools.package-data]
hyperon = [ "*.so", "*.dylib" ]
