name: ci auto

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  ci-auto-unix:
    uses: ./.github/workflows/common.yml
    with:
      python-version: "3.7"
      os: "ubuntu-22.04"
      cmake-version: "3.24.x"

  ci-auto-windows:
    uses: ./.github/workflows/common.yml
    with:
      python-version: "3.7"
      os: "windows-latest"
      cmake-version: "3.24.x"