name: ci auto

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  ci-auto:
    uses: ./.github/workflows/common.yml
    with:
      python-version: "3.7"
      os: "ubuntu-20.04"
      cmake-version: "3.19.x"
