name: ci auto

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  ci-auto:
    uses: ./.github/workflows/common.yml
    with:
      python-version: "3.8"
      os: "ubuntu-22.04"
      cmake-version: "3.24.x"
      build-type: "Debug"
